---
title: "Struture of the Book"
output: html_document
---

# Structure of the book

The preface of the book focuses on a short description of the authors, a short introduction to the book itself, an explanation of what R is and how it can be used, as well as the first steps of a project with R (including the linkage between R and GitHub). The preface is therefore a basic introduction to R and how projects are and can be designed. The first chapter of the book then focuses on source and output files. It is a continuation of the preface with much more detail on how R can be used and how data is imported into R. The first chapter therefore includes topics such as R Markdown files, importing data into R, using R as a calculator and using data structures. Note: The preface and first chapter of the book are fundaments of how to work with R and how to get started. Therefore, it is important to read these two parts of the book very carefully for the first time and follow every step carefully. The second chapter of the book then focuses on how to use R for data science. The knowledge of the first chapter should therefore be utilized for the second chapter of the book. For the chapter of data science or data analysis, we have decided to meke use R basics, in order to analyze various data (e.g. simple functions on vectors, subsetting, functions etc.). The final chapter of the book then focuses on tidyverse, which is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. 

To sum it up, this book is a reference for working with R as a tool or language for data science. Make sure to make use of the Pareto principle (80/20 rule) when reading it. Not all sections are equally useful or important to the particular book or even books that you intend to write.
