# (PART) Tidyverse Packages {-}

# What is `tidyverse` {#tidyverse}

As already mentioned in the preface of the book, many of the functions available in R come in packages. The tidyverse is a collection or bundle of open source R packages introduced by Hadley Wickham (Statistician from New Zealand who is currently Chief Scientist at RStudio) and his team. The fundamental packages of `tidyverse` are dplyr, tidyr, readr, tibble, stringr, ggplot2 and many other packages that provide the functionality to model, transform and visualize data. In general, the packages provided with `tidyverse` make R even better, faster, simpler and just more beautiful. The huge benefits of embracing the `tidyverse` come at the cost needing to learn a sub-dialect of R. This can be daunting for a beginner in R programming that put lots of effort into learning basic R functions. In general, tidyverse packages are intended to make the various processes of statistics and data science more productive through a variety of workflows. It is also the case that the tidyverse is work in progress. 

The next chapters all develop a relevant package, selected from the `tidyverse`. The list of all packages along with a fuller description of the system can be found on [tidyverse.org](https://www.tidyverse.org/).

Let's begin with the installation process of `tidyverse`:

```r
install.packages("tidyverse")
```
